// Code generated by protoc-gen-go.
// source: openinstrument.proto
// DO NOT EDIT!

/*
Package openinstrument_proto is a generated protocol buffer package.

It is generated from these files:
	openinstrument.proto

It has these top-level messages:
	LogMessage
	OperationLog
	StreamVariable
	StreamMutation
	StreamAggregation
	Value
	ValueStream
	Query
	GetRequest
	GetResponse
	AddRequest
	AddResponse
	ListRequest
	ListResponse
	BlockHeaderIndex
	BlockHeader
	RetentionPolicyItem
	RetentionPolicy
	ClusterMember
	ClusterConfig
	Block
	LookupBlockRequest
	LookupBlockResponse
	SplitBlockRequest
	SplitBlockResponse
	JoinBlockRequest
	JoinBlockResponse
	CompactBlockRequest
	CompactBlockResponse
	GetClusterRequest
	GetClusterResponse
	JoinClusterRequest
	JoinClusterResponse
	UpdateClusterRequest
	UpdateClusterResponse
	WatchClusterRequest
	WatchClusterResponse
	UpdateRetentionPolicyRequest
	UpdateRetentionPolicyResponse
*/
package openinstrument_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type StreamVariable_ValueType int32

const (
	StreamVariable_UNKNOWN StreamVariable_ValueType = 0
	StreamVariable_GAUGE   StreamVariable_ValueType = 1
	StreamVariable_RATE    StreamVariable_ValueType = 2
)

var StreamVariable_ValueType_name = map[int32]string{
	0: "UNKNOWN",
	1: "GAUGE",
	2: "RATE",
}
var StreamVariable_ValueType_value = map[string]int32{
	"UNKNOWN": 0,
	"GAUGE":   1,
	"RATE":    2,
}

func (x StreamVariable_ValueType) String() string {
	return proto.EnumName(StreamVariable_ValueType_name, int32(x))
}
func (StreamVariable_ValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type StreamMutation_SampleType int32

const (
	// Do not modify the data at all
	StreamMutation_NONE StreamMutation_SampleType = 0
	// Average out values between each sampling point
	StreamMutation_MEAN StreamMutation_SampleType = 1
	// Get the maximum value between each sampling point
	StreamMutation_MAX StreamMutation_SampleType = 2
	// Get the minimum value between each sampling point
	StreamMutation_MIN StreamMutation_SampleType = 3
	// Get the positive rate between each sampling point
	StreamMutation_RATE StreamMutation_SampleType = 4
	// Get the (possibly) negative rate between each sampling point
	StreamMutation_RATE_SIGNED StreamMutation_SampleType = 5
	// Modify timestamps and values so that frequency (interval between consecutive samples) is constant (specify in param)
	// Extra values between each sample will be aggregated according to <sample_type>.
	// Gaps in the stream less than <max_gap_interpolate> samples will be filled with interpolated values between the
	// closest real values.
	StreamMutation_INTERPOLATE StreamMutation_SampleType = 6
	// Last point in a time bracket (specified in param)
	StreamMutation_LAST StreamMutation_SampleType = 7
	// First point in a time bracket (specified in param)
	StreamMutation_FIRST StreamMutation_SampleType = 8
	// Multiply all values by a constant (specify in param)
	StreamMutation_MULTIPLY StreamMutation_SampleType = 9
	// Add a constant to each value (specify in param)
	StreamMutation_ADD StreamMutation_SampleType = 10
	// Get the nth root of each value (specify in param)
	StreamMutation_ROOT StreamMutation_SampleType = 11
	// Get the nth power of each value (specify in param)
	StreamMutation_POWER StreamMutation_SampleType = 12
	// Moving average over a time period (specified in param)
	StreamMutation_MOVING_AVERAGE StreamMutation_SampleType = 13
)

var StreamMutation_SampleType_name = map[int32]string{
	0:  "NONE",
	1:  "MEAN",
	2:  "MAX",
	3:  "MIN",
	4:  "RATE",
	5:  "RATE_SIGNED",
	6:  "INTERPOLATE",
	7:  "LAST",
	8:  "FIRST",
	9:  "MULTIPLY",
	10: "ADD",
	11: "ROOT",
	12: "POWER",
	13: "MOVING_AVERAGE",
}
var StreamMutation_SampleType_value = map[string]int32{
	"NONE":           0,
	"MEAN":           1,
	"MAX":            2,
	"MIN":            3,
	"RATE":           4,
	"RATE_SIGNED":    5,
	"INTERPOLATE":    6,
	"LAST":           7,
	"FIRST":          8,
	"MULTIPLY":       9,
	"ADD":            10,
	"ROOT":           11,
	"POWER":          12,
	"MOVING_AVERAGE": 13,
}

func (x StreamMutation_SampleType) String() string {
	return proto.EnumName(StreamMutation_SampleType_name, int32(x))
}
func (StreamMutation_SampleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type StreamAggregation_AggregateType int32

const (
	// Do not aggregate between streams
	StreamAggregation_NONE StreamAggregation_AggregateType = 0
	// Get the mean of all values at a common time across streams
	StreamAggregation_MEAN StreamAggregation_AggregateType = 1
	// Get the maximum of all values at a common time across streams
	StreamAggregation_MAX StreamAggregation_AggregateType = 2
	// Get the minimum of all values at a common time across streams
	StreamAggregation_MIN StreamAggregation_AggregateType = 3
	// Get the median of all values at a common time across streams
	StreamAggregation_MEDIAN StreamAggregation_AggregateType = 4
	// Get the total of all values at a common time across streams
	StreamAggregation_SUM StreamAggregation_AggregateType = 5
	// Get the standard deviation of all values at a common time across streams
	StreamAggregation_STDDEV StreamAggregation_AggregateType = 6
	// Get a particular percentile (provided in param) of all values at a common time across streams
	StreamAggregation_PERCENTILE StreamAggregation_AggregateType = 7
)

var StreamAggregation_AggregateType_name = map[int32]string{
	0: "NONE",
	1: "MEAN",
	2: "MAX",
	3: "MIN",
	4: "MEDIAN",
	5: "SUM",
	6: "STDDEV",
	7: "PERCENTILE",
}
var StreamAggregation_AggregateType_value = map[string]int32{
	"NONE":       0,
	"MEAN":       1,
	"MAX":        2,
	"MIN":        3,
	"MEDIAN":     4,
	"SUM":        5,
	"STDDEV":     6,
	"PERCENTILE": 7,
}

func (x StreamAggregation_AggregateType) String() string {
	return proto.EnumName(StreamAggregation_AggregateType_name, int32(x))
}
func (StreamAggregation_AggregateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type RetentionPolicyItem_Target int32

const (
	RetentionPolicyItem_KEEP RetentionPolicyItem_Target = 0
	RetentionPolicyItem_DROP RetentionPolicyItem_Target = 1
)

var RetentionPolicyItem_Target_name = map[int32]string{
	0: "KEEP",
	1: "DROP",
}
var RetentionPolicyItem_Target_value = map[string]int32{
	"KEEP": 0,
	"DROP": 1,
}

func (x RetentionPolicyItem_Target) String() string {
	return proto.EnumName(RetentionPolicyItem_Target_name, int32(x))
}
func (RetentionPolicyItem_Target) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16, 0}
}

type ClusterMember_State int32

const (
	ClusterMember_UNKNOWN  ClusterMember_State = 0
	ClusterMember_LOAD     ClusterMember_State = 1
	ClusterMember_RUN      ClusterMember_State = 2
	ClusterMember_DRAIN    ClusterMember_State = 3
	ClusterMember_READONLY ClusterMember_State = 4
	ClusterMember_SHUTDOWN ClusterMember_State = 5
)

var ClusterMember_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOAD",
	2: "RUN",
	3: "DRAIN",
	4: "READONLY",
	5: "SHUTDOWN",
}
var ClusterMember_State_value = map[string]int32{
	"UNKNOWN":  0,
	"LOAD":     1,
	"RUN":      2,
	"DRAIN":    3,
	"READONLY": 4,
	"SHUTDOWN": 5,
}

func (x ClusterMember_State) String() string {
	return proto.EnumName(ClusterMember_State_name, int32(x))
}
func (ClusterMember_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{18, 0} }

type Block_State int32

const (
	Block_UNKNOWN    Block_State = 0
	Block_LOADING    Block_State = 1
	Block_LIVE       Block_State = 2
	Block_COMPACTING Block_State = 3
	Block_MIGRATING  Block_State = 4
	Block_UNLOADING  Block_State = 5
	Block_UNLOADED   Block_State = 6
	Block_DESTROYED  Block_State = 7
)

var Block_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOADING",
	2: "LIVE",
	3: "COMPACTING",
	4: "MIGRATING",
	5: "UNLOADING",
	6: "UNLOADED",
	7: "DESTROYED",
}
var Block_State_value = map[string]int32{
	"UNKNOWN":    0,
	"LOADING":    1,
	"LIVE":       2,
	"COMPACTING": 3,
	"MIGRATING":  4,
	"UNLOADING":  5,
	"UNLOADED":   6,
	"DESTROYED":  7,
}

func (x Block_State) String() string {
	return proto.EnumName(Block_State_name, int32(x))
}
func (Block_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{20, 0} }

type UpdateRetentionPolicyRequest_Operation int32

const (
	UpdateRetentionPolicyRequest_UNKNOWN UpdateRetentionPolicyRequest_Operation = 0
	UpdateRetentionPolicyRequest_APPEND  UpdateRetentionPolicyRequest_Operation = 1
	UpdateRetentionPolicyRequest_INSERT  UpdateRetentionPolicyRequest_Operation = 2
	UpdateRetentionPolicyRequest_REMOVE  UpdateRetentionPolicyRequest_Operation = 3
)

var UpdateRetentionPolicyRequest_Operation_name = map[int32]string{
	0: "UNKNOWN",
	1: "APPEND",
	2: "INSERT",
	3: "REMOVE",
}
var UpdateRetentionPolicyRequest_Operation_value = map[string]int32{
	"UNKNOWN": 0,
	"APPEND":  1,
	"INSERT":  2,
	"REMOVE":  3,
}

func (x UpdateRetentionPolicyRequest_Operation) String() string {
	return proto.EnumName(UpdateRetentionPolicyRequest_Operation_name, int32(x))
}
func (UpdateRetentionPolicyRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{37, 0}
}

type LogMessage struct {
	Timestamp    uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	EndTimestamp uint64 `protobuf:"varint,3,opt,name=end_timestamp" json:"end_timestamp,omitempty"`
	Message      string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *LogMessage) Reset()                    { *m = LogMessage{} }
func (m *LogMessage) String() string            { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()               {}
func (*LogMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OperationLog struct {
	Log []*LogMessage `protobuf:"bytes,1,rep,name=log" json:"log,omitempty"`
}

func (m *OperationLog) Reset()                    { *m = OperationLog{} }
func (m *OperationLog) String() string            { return proto.CompactTextString(m) }
func (*OperationLog) ProtoMessage()               {}
func (*OperationLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OperationLog) GetLog() []*LogMessage {
	if m != nil {
		return m.Log
	}
	return nil
}

type StreamVariable struct {
	Name  string                   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Label map[string]string        `protobuf:"bytes,2,rep,name=label" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type  StreamVariable_ValueType `protobuf:"varint,3,opt,name=type,enum=openinstrument.proto.StreamVariable_ValueType" json:"type,omitempty"`
	// Milliseconds since epoch, or if negative, milliseconds before now.
	MinTimestamp int64 `protobuf:"varint,4,opt,name=min_timestamp" json:"min_timestamp,omitempty"`
	MaxTimestamp int64 `protobuf:"varint,5,opt,name=max_timestamp" json:"max_timestamp,omitempty"`
}

func (m *StreamVariable) Reset()                    { *m = StreamVariable{} }
func (m *StreamVariable) String() string            { return proto.CompactTextString(m) }
func (*StreamVariable) ProtoMessage()               {}
func (*StreamVariable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StreamVariable) GetLabel() map[string]string {
	if m != nil {
		return m.Label
	}
	return nil
}

// Mutations return a modified copy of every input query
type StreamMutation struct {
	Type  StreamMutation_SampleType `protobuf:"varint,1,opt,name=type,enum=openinstrument.proto.StreamMutation_SampleType" json:"type,omitempty"`
	Param float64                   `protobuf:"fixed64,2,opt,name=param" json:"param,omitempty"`
	// Input query
	Query *Query `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	// Gaps in the stream of more than <max_gap_interpolate> samples will not be filled.
	MaxGapInterpolate uint32 `protobuf:"varint,4,opt,name=max_gap_interpolate" json:"max_gap_interpolate,omitempty"`
	SampleFrequency   uint32 `protobuf:"varint,5,opt,name=sample_frequency" json:"sample_frequency,omitempty"`
}

func (m *StreamMutation) Reset()                    { *m = StreamMutation{} }
func (m *StreamMutation) String() string            { return proto.CompactTextString(m) }
func (*StreamMutation) ProtoMessage()               {}
func (*StreamMutation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StreamMutation) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

// Aggregations return a single output stream, built from the combination of every input query
type StreamAggregation struct {
	Type StreamAggregation_AggregateType `protobuf:"varint,1,opt,name=type,enum=openinstrument.proto.StreamAggregation_AggregateType" json:"type,omitempty"`
	// Labels to aggregate by on the input streams. If no labels are specified, aggregation will be done on the variable
	// only.
	Label []string `protobuf:"bytes,2,rep,name=label" json:"label,omitempty"`
	// Points will be aggregated if they are less than sample_interval ms apart. Default is 30 seconds.
	SampleInterval uint32 `protobuf:"varint,3,opt,name=sample_interval" json:"sample_interval,omitempty"`
	// Optional parameter
	Param float64 `protobuf:"fixed64,4,opt,name=param" json:"param,omitempty"`
	// Input query
	Query []*Query `protobuf:"bytes,5,rep,name=query" json:"query,omitempty"`
}

func (m *StreamAggregation) Reset()                    { *m = StreamAggregation{} }
func (m *StreamAggregation) String() string            { return proto.CompactTextString(m) }
func (*StreamAggregation) ProtoMessage()               {}
func (*StreamAggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StreamAggregation) GetQuery() []*Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type Value struct {
	// Milliseconds since epoch
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Value_Double
	//	*Value_String_
	Value isValue_Value `protobuf_oneof:"value"`
	// Used for run-length encoding
	EndTimestamp uint64 `protobuf:"varint,4,opt,name=end_timestamp" json:"end_timestamp,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isValue_Value interface {
	isValue_Value()
}

type Value_Double struct {
	Double float64 `protobuf:"fixed64,2,opt,name=double,oneof"`
}
type Value_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=string,oneof"`
}

func (*Value_Double) isValue_Value()  {}
func (*Value_String_) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetDouble() float64 {
	if x, ok := m.GetValue().(*Value_Double); ok {
		return x.Double
	}
	return 0
}

func (m *Value) GetString_() string {
	if x, ok := m.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_Double)(nil),
		(*Value_String_)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Double:
		b.EncodeVarint(2<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Double))
	case *Value_String_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 2: // value.double
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_Double{math.Float64frombits(x)}
		return true, err
	case 3: // value.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_String_{x}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Double:
		n += proto.SizeVarint(2<<3 | proto.WireFixed64)
		n += 8
	case *Value_String_:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ValueStream struct {
	Variable *StreamVariable `protobuf:"bytes,2,opt,name=variable" json:"variable,omitempty"`
	Value    []*Value        `protobuf:"bytes,4,rep,name=value" json:"value,omitempty"`
	// An optional set of mutations that have been applied to this stream.
	// If the stream contains the raw data, this should be empty.
	Mutation []*StreamMutation `protobuf:"bytes,5,rep,name=mutation" json:"mutation,omitempty"`
}

func (m *ValueStream) Reset()                    { *m = ValueStream{} }
func (m *ValueStream) String() string            { return proto.CompactTextString(m) }
func (*ValueStream) ProtoMessage()               {}
func (*ValueStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ValueStream) GetVariable() *StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *ValueStream) GetValue() []*Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueStream) GetMutation() []*StreamMutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

// Queries return a stream for every input variable / mutation / aggregation
type Query struct {
	Variable    []*StreamVariable    `protobuf:"bytes,1,rep,name=variable" json:"variable,omitempty"`
	Mutation    []*StreamMutation    `protobuf:"bytes,2,rep,name=mutation" json:"mutation,omitempty"`
	Aggregation []*StreamAggregation `protobuf:"bytes,3,rep,name=aggregation" json:"aggregation,omitempty"`
	Constant    []float64            `protobuf:"fixed64,4,rep,name=constant" json:"constant,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Query) GetVariable() []*StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *Query) GetMutation() []*StreamMutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (m *Query) GetAggregation() []*StreamAggregation {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

type GetRequest struct {
	Query *Query `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	// deprecated
	Variable *StreamVariable `protobuf:"bytes,9,opt,name=variable" json:"variable,omitempty"`
	// If mutations or aggregations are supplied, the GetResponse will have a separate stream for each change requested.
	Mutation    []*StreamMutation    `protobuf:"bytes,6,rep,name=mutation" json:"mutation,omitempty"`
	Aggregation []*StreamAggregation `protobuf:"bytes,7,rep,name=aggregation" json:"aggregation,omitempty"`
	// Limit to how many variables can be returned in a standard GetRequest. This can be overridden if required.
	MaxVariables uint32 `protobuf:"varint,8,opt,name=max_variables" json:"max_variables,omitempty"`
	// This request has been forwarded by another store server and should not be forwarded again.
	// This shouldn't happen but is here as a failsafe.
	Forwarded bool `protobuf:"varint,10,opt,name=forwarded" json:"forwarded,omitempty"`
	// Limit the number of values that can be returned for each variable.
	MaxValues uint32 `protobuf:"varint,11,opt,name=max_values" json:"max_values,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GetRequest) GetVariable() *StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *GetRequest) GetMutation() []*StreamMutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (m *GetRequest) GetAggregation() []*StreamAggregation {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

type GetResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Errormessage string `protobuf:"bytes,2,opt,name=errormessage" json:"errormessage,omitempty"`
	// Contains a separate stream for every mutation requested in GetRequest, in the same order. If no mutations are
	// requested, the response will contain a single stream of the raw data.
	Stream []*ValueStream `protobuf:"bytes,3,rep,name=stream" json:"stream,omitempty"`
	Timer  []*LogMessage  `protobuf:"bytes,4,rep,name=timer" json:"timer,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetResponse) GetStream() []*ValueStream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *GetResponse) GetTimer() []*LogMessage {
	if m != nil {
		return m.Timer
	}
	return nil
}

type AddRequest struct {
	Stream []*ValueStream `protobuf:"bytes,1,rep,name=stream" json:"stream,omitempty"`
	// This request has been forwarded by another store server and should not be forwarded again.
	// This shouldn't happen but is here as a failsafe.
	Forwarded bool `protobuf:"varint,2,opt,name=forwarded" json:"forwarded,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AddRequest) GetStream() []*ValueStream {
	if m != nil {
		return m.Stream
	}
	return nil
}

type AddResponse struct {
	Success      bool          `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Errormessage string        `protobuf:"bytes,2,opt,name=errormessage" json:"errormessage,omitempty"`
	Timer        []*LogMessage `protobuf:"bytes,3,rep,name=timer" json:"timer,omitempty"`
	Streams      uint32        `protobuf:"varint,4,opt,name=streams" json:"streams,omitempty"`
	Values       uint32        `protobuf:"varint,5,opt,name=values" json:"values,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AddResponse) GetTimer() []*LogMessage {
	if m != nil {
		return m.Timer
	}
	return nil
}

type ListRequest struct {
	Prefix *StreamVariable `protobuf:"bytes,3,opt,name=prefix" json:"prefix,omitempty"`
	// Limit to how many variables can be returned in a standard ListRequest. This can be overridden if required.
	MaxVariables uint32 `protobuf:"varint,2,opt,name=max_variables" json:"max_variables,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListRequest) GetPrefix() *StreamVariable {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type ListResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Errormessage string `protobuf:"bytes,2,opt,name=errormessage" json:"errormessage,omitempty"`
	// Although this uses the ValueStream for returning a list of variables, the expectation is that the value field is
	// empty.
	Stream   []*ValueStream    `protobuf:"bytes,3,rep,name=stream" json:"stream,omitempty"`
	Variable []*StreamVariable `protobuf:"bytes,4,rep,name=variable" json:"variable,omitempty"`
	Timer    []*LogMessage     `protobuf:"bytes,5,rep,name=timer" json:"timer,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListResponse) GetStream() []*ValueStream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *ListResponse) GetVariable() []*StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *ListResponse) GetTimer() []*LogMessage {
	if m != nil {
		return m.Timer
	}
	return nil
}

type BlockHeaderIndex struct {
	Variable     *StreamVariable `protobuf:"bytes,1,opt,name=variable" json:"variable,omitempty"`
	Offset       uint64          `protobuf:"fixed64,2,opt,name=offset" json:"offset,omitempty"`
	NumValues    uint32          `protobuf:"fixed32,3,opt,name=num_values" json:"num_values,omitempty"`
	MinTimestamp uint64          `protobuf:"fixed64,4,opt,name=min_timestamp" json:"min_timestamp,omitempty"`
	MaxTimestamp uint64          `protobuf:"fixed64,5,opt,name=max_timestamp" json:"max_timestamp,omitempty"`
}

func (m *BlockHeaderIndex) Reset()                    { *m = BlockHeaderIndex{} }
func (m *BlockHeaderIndex) String() string            { return proto.CompactTextString(m) }
func (*BlockHeaderIndex) ProtoMessage()               {}
func (*BlockHeaderIndex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BlockHeaderIndex) GetVariable() *StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type BlockHeader struct {
	Version        uint32              `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	StartTimestamp uint64              `protobuf:"varint,1,opt,name=start_timestamp" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64              `protobuf:"varint,2,opt,name=end_timestamp" json:"end_timestamp,omitempty"`
	Index          []*BlockHeaderIndex `protobuf:"bytes,5,rep,name=index" json:"index,omitempty"`
	EndKey         string              `protobuf:"bytes,7,opt,name=end_key" json:"end_key,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *BlockHeader) GetIndex() []*BlockHeaderIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

type RetentionPolicyItem struct {
	Variable []*StreamVariable          `protobuf:"bytes,1,rep,name=variable" json:"variable,omitempty"`
	Comment  []string                   `protobuf:"bytes,2,rep,name=comment" json:"comment,omitempty"`
	Policy   RetentionPolicyItem_Target `protobuf:"varint,3,opt,name=policy,enum=openinstrument.proto.RetentionPolicyItem_Target" json:"policy,omitempty"`
	Mutation []*StreamMutation          `protobuf:"bytes,4,rep,name=mutation" json:"mutation,omitempty"`
}

func (m *RetentionPolicyItem) Reset()                    { *m = RetentionPolicyItem{} }
func (m *RetentionPolicyItem) String() string            { return proto.CompactTextString(m) }
func (*RetentionPolicyItem) ProtoMessage()               {}
func (*RetentionPolicyItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RetentionPolicyItem) GetVariable() []*StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *RetentionPolicyItem) GetMutation() []*StreamMutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

type RetentionPolicy struct {
	Policy   []*RetentionPolicyItem `protobuf:"bytes,1,rep,name=policy" json:"policy,omitempty"`
	Interval uint32                 `protobuf:"varint,2,opt,name=interval" json:"interval,omitempty"`
}

func (m *RetentionPolicy) Reset()                    { *m = RetentionPolicy{} }
func (m *RetentionPolicy) String() string            { return proto.CompactTextString(m) }
func (*RetentionPolicy) ProtoMessage()               {}
func (*RetentionPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RetentionPolicy) GetPolicy() []*RetentionPolicyItem {
	if m != nil {
		return m.Policy
	}
	return nil
}

type ClusterMember struct {
	Address     string              `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	State       ClusterMember_State `protobuf:"varint,2,opt,name=state,enum=openinstrument.proto.ClusterMember_State" json:"state,omitempty"`
	LastUpdated uint64              `protobuf:"varint,3,opt,name=last_updated" json:"last_updated,omitempty"`
	Name        string              `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterMember) Reset()                    { *m = ClusterMember{} }
func (m *ClusterMember) String() string            { return proto.CompactTextString(m) }
func (*ClusterMember) ProtoMessage()               {}
func (*ClusterMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type ClusterConfig struct {
	Server          []*ClusterMember `protobuf:"bytes,1,rep,name=server" json:"server,omitempty"`
	Block           []*Block         `protobuf:"bytes,2,rep,name=block" json:"block,omitempty"`
	RetentionPolicy *RetentionPolicy `protobuf:"bytes,3,opt,name=retention_policy" json:"retention_policy,omitempty"`
}

func (m *ClusterConfig) Reset()                    { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string            { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()               {}
func (*ClusterConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ClusterConfig) GetServer() []*ClusterMember {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ClusterConfig) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ClusterConfig) GetRetentionPolicy() *RetentionPolicy {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

type Block struct {
	Header           *BlockHeader `protobuf:"bytes,17,opt,name=header" json:"header,omitempty"`
	Id               string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	EndKey           string       `protobuf:"bytes,2,opt,name=end_key" json:"end_key,omitempty"`
	State            Block_State  `protobuf:"varint,3,opt,name=state,enum=openinstrument.proto.Block_State" json:"state,omitempty"`
	IndexedStreams   uint32       `protobuf:"varint,4,opt,name=indexed_streams" json:"indexed_streams,omitempty"`
	IndexedValues    uint32       `protobuf:"varint,5,opt,name=indexed_values" json:"indexed_values,omitempty"`
	LoggedStreams    uint32       `protobuf:"varint,6,opt,name=logged_streams" json:"logged_streams,omitempty"`
	LoggedValues     uint32       `protobuf:"varint,7,opt,name=logged_values" json:"logged_values,omitempty"`
	UnloggedStreams  uint32       `protobuf:"varint,8,opt,name=unlogged_streams" json:"unlogged_streams,omitempty"`
	UnloggedValues   uint32       `protobuf:"varint,9,opt,name=unlogged_values" json:"unlogged_values,omitempty"`
	CompactDuration  string       `protobuf:"bytes,10,opt,name=compact_duration" json:"compact_duration,omitempty"`
	CompactStartTime uint64       `protobuf:"varint,11,opt,name=compact_start_time" json:"compact_start_time,omitempty"`
	CompactEndTime   uint64       `protobuf:"varint,12,opt,name=compact_end_time" json:"compact_end_time,omitempty"`
	Node             string       `protobuf:"bytes,13,opt,name=node" json:"node,omitempty"`
	DestinationNode  string       `protobuf:"bytes,14,opt,name=destination_node" json:"destination_node,omitempty"`
	LastUpdated      uint64       `protobuf:"varint,16,opt,name=last_updated" json:"last_updated,omitempty"`
	// Bytes
	Size uint32 `protobuf:"varint,18,opt,name=size" json:"size,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type LookupBlockRequest struct {
	Variable *StreamVariable `protobuf:"bytes,1,opt,name=variable" json:"variable,omitempty"`
	BlockId  string          `protobuf:"bytes,2,opt,name=block_id" json:"block_id,omitempty"`
}

func (m *LookupBlockRequest) Reset()                    { *m = LookupBlockRequest{} }
func (m *LookupBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupBlockRequest) ProtoMessage()               {}
func (*LookupBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *LookupBlockRequest) GetVariable() *StreamVariable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type LookupBlockResponse struct {
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *LookupBlockResponse) Reset()                    { *m = LookupBlockResponse{} }
func (m *LookupBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupBlockResponse) ProtoMessage()               {}
func (*LookupBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *LookupBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SplitBlockRequest struct {
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *SplitBlockRequest) Reset()                    { *m = SplitBlockRequest{} }
func (m *SplitBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*SplitBlockRequest) ProtoMessage()               {}
func (*SplitBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *SplitBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SplitBlockResponse struct {
	Block []*Block `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
}

func (m *SplitBlockResponse) Reset()                    { *m = SplitBlockResponse{} }
func (m *SplitBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*SplitBlockResponse) ProtoMessage()               {}
func (*SplitBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *SplitBlockResponse) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type JoinBlockRequest struct {
	// This the last block in the sequence. The block with the previous end key
	// will be joined with this one, so the output block will have the same end
	// key, but a different ID.
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *JoinBlockRequest) Reset()                    { *m = JoinBlockRequest{} }
func (m *JoinBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinBlockRequest) ProtoMessage()               {}
func (*JoinBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *JoinBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type JoinBlockResponse struct {
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *JoinBlockResponse) Reset()                    { *m = JoinBlockResponse{} }
func (m *JoinBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinBlockResponse) ProtoMessage()               {}
func (*JoinBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *JoinBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type CompactBlockRequest struct {
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *CompactBlockRequest) Reset()                    { *m = CompactBlockRequest{} }
func (m *CompactBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*CompactBlockRequest) ProtoMessage()               {}
func (*CompactBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *CompactBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type CompactBlockResponse struct {
	Block *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *CompactBlockResponse) Reset()                    { *m = CompactBlockResponse{} }
func (m *CompactBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*CompactBlockResponse) ProtoMessage()               {}
func (*CompactBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *CompactBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetClusterRequest struct {
}

func (m *GetClusterRequest) Reset()                    { *m = GetClusterRequest{} }
func (m *GetClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*GetClusterRequest) ProtoMessage()               {}
func (*GetClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type GetClusterResponse struct {
	Config *ClusterConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *GetClusterResponse) Reset()                    { *m = GetClusterResponse{} }
func (m *GetClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*GetClusterResponse) ProtoMessage()               {}
func (*GetClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GetClusterResponse) GetConfig() *ClusterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type JoinClusterRequest struct {
	Member *ClusterMember `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *JoinClusterRequest) Reset()                    { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()               {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *JoinClusterRequest) GetMember() *ClusterMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type JoinClusterResponse struct {
	Member []*ClusterMember `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
}

func (m *JoinClusterResponse) Reset()                    { *m = JoinClusterResponse{} }
func (m *JoinClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterResponse) ProtoMessage()               {}
func (*JoinClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *JoinClusterResponse) GetMember() []*ClusterMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateClusterRequest struct {
	Member []*ClusterMember `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
}

func (m *UpdateClusterRequest) Reset()                    { *m = UpdateClusterRequest{} }
func (m *UpdateClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateClusterRequest) ProtoMessage()               {}
func (*UpdateClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *UpdateClusterRequest) GetMember() []*ClusterMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateClusterResponse struct {
	Member []*ClusterMember `protobuf:"bytes,1,rep,name=member" json:"member,omitempty"`
}

func (m *UpdateClusterResponse) Reset()                    { *m = UpdateClusterResponse{} }
func (m *UpdateClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateClusterResponse) ProtoMessage()               {}
func (*UpdateClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *UpdateClusterResponse) GetMember() []*ClusterMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type WatchClusterRequest struct {
}

func (m *WatchClusterRequest) Reset()                    { *m = WatchClusterRequest{} }
func (m *WatchClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchClusterRequest) ProtoMessage()               {}
func (*WatchClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type WatchClusterResponse struct {
	Config *ClusterConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *WatchClusterResponse) Reset()                    { *m = WatchClusterResponse{} }
func (m *WatchClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchClusterResponse) ProtoMessage()               {}
func (*WatchClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *WatchClusterResponse) GetConfig() *ClusterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type UpdateRetentionPolicyRequest struct {
	Op   UpdateRetentionPolicyRequest_Operation `protobuf:"varint,1,opt,name=op,enum=openinstrument.proto.UpdateRetentionPolicyRequest_Operation" json:"op,omitempty"`
	Item *RetentionPolicyItem                   `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
	// 0-indexed position for insert or remove
	Position uint32 `protobuf:"varint,3,opt,name=position" json:"position,omitempty"`
}

func (m *UpdateRetentionPolicyRequest) Reset()                    { *m = UpdateRetentionPolicyRequest{} }
func (m *UpdateRetentionPolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRetentionPolicyRequest) ProtoMessage()               {}
func (*UpdateRetentionPolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *UpdateRetentionPolicyRequest) GetItem() *RetentionPolicyItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateRetentionPolicyResponse struct {
	Policy *RetentionPolicy `protobuf:"bytes,1,opt,name=policy" json:"policy,omitempty"`
}

func (m *UpdateRetentionPolicyResponse) Reset()                    { *m = UpdateRetentionPolicyResponse{} }
func (m *UpdateRetentionPolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateRetentionPolicyResponse) ProtoMessage()               {}
func (*UpdateRetentionPolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *UpdateRetentionPolicyResponse) GetPolicy() *RetentionPolicy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func init() {
	proto.RegisterType((*LogMessage)(nil), "openinstrument.proto.LogMessage")
	proto.RegisterType((*OperationLog)(nil), "openinstrument.proto.OperationLog")
	proto.RegisterType((*StreamVariable)(nil), "openinstrument.proto.StreamVariable")
	proto.RegisterType((*StreamMutation)(nil), "openinstrument.proto.StreamMutation")
	proto.RegisterType((*StreamAggregation)(nil), "openinstrument.proto.StreamAggregation")
	proto.RegisterType((*Value)(nil), "openinstrument.proto.Value")
	proto.RegisterType((*ValueStream)(nil), "openinstrument.proto.ValueStream")
	proto.RegisterType((*Query)(nil), "openinstrument.proto.Query")
	proto.RegisterType((*GetRequest)(nil), "openinstrument.proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "openinstrument.proto.GetResponse")
	proto.RegisterType((*AddRequest)(nil), "openinstrument.proto.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "openinstrument.proto.AddResponse")
	proto.RegisterType((*ListRequest)(nil), "openinstrument.proto.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "openinstrument.proto.ListResponse")
	proto.RegisterType((*BlockHeaderIndex)(nil), "openinstrument.proto.BlockHeaderIndex")
	proto.RegisterType((*BlockHeader)(nil), "openinstrument.proto.BlockHeader")
	proto.RegisterType((*RetentionPolicyItem)(nil), "openinstrument.proto.RetentionPolicyItem")
	proto.RegisterType((*RetentionPolicy)(nil), "openinstrument.proto.RetentionPolicy")
	proto.RegisterType((*ClusterMember)(nil), "openinstrument.proto.ClusterMember")
	proto.RegisterType((*ClusterConfig)(nil), "openinstrument.proto.ClusterConfig")
	proto.RegisterType((*Block)(nil), "openinstrument.proto.Block")
	proto.RegisterType((*LookupBlockRequest)(nil), "openinstrument.proto.LookupBlockRequest")
	proto.RegisterType((*LookupBlockResponse)(nil), "openinstrument.proto.LookupBlockResponse")
	proto.RegisterType((*SplitBlockRequest)(nil), "openinstrument.proto.SplitBlockRequest")
	proto.RegisterType((*SplitBlockResponse)(nil), "openinstrument.proto.SplitBlockResponse")
	proto.RegisterType((*JoinBlockRequest)(nil), "openinstrument.proto.JoinBlockRequest")
	proto.RegisterType((*JoinBlockResponse)(nil), "openinstrument.proto.JoinBlockResponse")
	proto.RegisterType((*CompactBlockRequest)(nil), "openinstrument.proto.CompactBlockRequest")
	proto.RegisterType((*CompactBlockResponse)(nil), "openinstrument.proto.CompactBlockResponse")
	proto.RegisterType((*GetClusterRequest)(nil), "openinstrument.proto.GetClusterRequest")
	proto.RegisterType((*GetClusterResponse)(nil), "openinstrument.proto.GetClusterResponse")
	proto.RegisterType((*JoinClusterRequest)(nil), "openinstrument.proto.JoinClusterRequest")
	proto.RegisterType((*JoinClusterResponse)(nil), "openinstrument.proto.JoinClusterResponse")
	proto.RegisterType((*UpdateClusterRequest)(nil), "openinstrument.proto.UpdateClusterRequest")
	proto.RegisterType((*UpdateClusterResponse)(nil), "openinstrument.proto.UpdateClusterResponse")
	proto.RegisterType((*WatchClusterRequest)(nil), "openinstrument.proto.WatchClusterRequest")
	proto.RegisterType((*WatchClusterResponse)(nil), "openinstrument.proto.WatchClusterResponse")
	proto.RegisterType((*UpdateRetentionPolicyRequest)(nil), "openinstrument.proto.UpdateRetentionPolicyRequest")
	proto.RegisterType((*UpdateRetentionPolicyResponse)(nil), "openinstrument.proto.UpdateRetentionPolicyResponse")
	proto.RegisterEnum("openinstrument.proto.StreamVariable_ValueType", StreamVariable_ValueType_name, StreamVariable_ValueType_value)
	proto.RegisterEnum("openinstrument.proto.StreamMutation_SampleType", StreamMutation_SampleType_name, StreamMutation_SampleType_value)
	proto.RegisterEnum("openinstrument.proto.StreamAggregation_AggregateType", StreamAggregation_AggregateType_name, StreamAggregation_AggregateType_value)
	proto.RegisterEnum("openinstrument.proto.RetentionPolicyItem_Target", RetentionPolicyItem_Target_name, RetentionPolicyItem_Target_value)
	proto.RegisterEnum("openinstrument.proto.ClusterMember_State", ClusterMember_State_name, ClusterMember_State_value)
	proto.RegisterEnum("openinstrument.proto.Block_State", Block_State_name, Block_State_value)
	proto.RegisterEnum("openinstrument.proto.UpdateRetentionPolicyRequest_Operation", UpdateRetentionPolicyRequest_Operation_name, UpdateRetentionPolicyRequest_Operation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Store service

type StoreClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Store_GetClient, error)
	Add(ctx context.Context, opts ...grpc.CallOption) (Store_AddClient, error)
	UpdateRetentionPolicy(ctx context.Context, in *UpdateRetentionPolicyRequest, opts ...grpc.CallOption) (*UpdateRetentionPolicyResponse, error)
	LookupBlock(ctx context.Context, in *LookupBlockRequest, opts ...grpc.CallOption) (*LookupBlockResponse, error)
	SplitBlock(ctx context.Context, in *SplitBlockRequest, opts ...grpc.CallOption) (*SplitBlockResponse, error)
	JoinBlock(ctx context.Context, in *JoinBlockRequest, opts ...grpc.CallOption) (*JoinBlockResponse, error)
	CompactBlock(ctx context.Context, in *CompactBlockRequest, opts ...grpc.CallOption) (*CompactBlockResponse, error)
	GetCluster(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*GetClusterResponse, error)
	WatchCluster(ctx context.Context, in *WatchClusterRequest, opts ...grpc.CallOption) (Store_WatchClusterClient, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Store_GetClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Store_serviceDesc.Streams[0], c.cc, "/openinstrument.proto.Store/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Store_GetClient interface {
	Recv() (*GetResponse, error)
	grpc.ClientStream
}

type storeGetClient struct {
	grpc.ClientStream
}

func (x *storeGetClient) Recv() (*GetResponse, error) {
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeClient) Add(ctx context.Context, opts ...grpc.CallOption) (Store_AddClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Store_serviceDesc.Streams[1], c.cc, "/openinstrument.proto.Store/Add", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeAddClient{stream}
	return x, nil
}

type Store_AddClient interface {
	Send(*AddRequest) error
	Recv() (*AddResponse, error)
	grpc.ClientStream
}

type storeAddClient struct {
	grpc.ClientStream
}

func (x *storeAddClient) Send(m *AddRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeAddClient) Recv() (*AddResponse, error) {
	m := new(AddResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeClient) UpdateRetentionPolicy(ctx context.Context, in *UpdateRetentionPolicyRequest, opts ...grpc.CallOption) (*UpdateRetentionPolicyResponse, error) {
	out := new(UpdateRetentionPolicyResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/UpdateRetentionPolicy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) LookupBlock(ctx context.Context, in *LookupBlockRequest, opts ...grpc.CallOption) (*LookupBlockResponse, error) {
	out := new(LookupBlockResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/LookupBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) SplitBlock(ctx context.Context, in *SplitBlockRequest, opts ...grpc.CallOption) (*SplitBlockResponse, error) {
	out := new(SplitBlockResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/SplitBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) JoinBlock(ctx context.Context, in *JoinBlockRequest, opts ...grpc.CallOption) (*JoinBlockResponse, error) {
	out := new(JoinBlockResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/JoinBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) CompactBlock(ctx context.Context, in *CompactBlockRequest, opts ...grpc.CallOption) (*CompactBlockResponse, error) {
	out := new(CompactBlockResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/CompactBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetCluster(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*GetClusterResponse, error) {
	out := new(GetClusterResponse)
	err := grpc.Invoke(ctx, "/openinstrument.proto.Store/GetCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) WatchCluster(ctx context.Context, in *WatchClusterRequest, opts ...grpc.CallOption) (Store_WatchClusterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Store_serviceDesc.Streams[2], c.cc, "/openinstrument.proto.Store/WatchCluster", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeWatchClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Store_WatchClusterClient interface {
	Recv() (*WatchClusterResponse, error)
	grpc.ClientStream
}

type storeWatchClusterClient struct {
	grpc.ClientStream
}

func (x *storeWatchClusterClient) Recv() (*WatchClusterResponse, error) {
	m := new(WatchClusterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Store service

type StoreServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Get(*GetRequest, Store_GetServer) error
	Add(Store_AddServer) error
	UpdateRetentionPolicy(context.Context, *UpdateRetentionPolicyRequest) (*UpdateRetentionPolicyResponse, error)
	LookupBlock(context.Context, *LookupBlockRequest) (*LookupBlockResponse, error)
	SplitBlock(context.Context, *SplitBlockRequest) (*SplitBlockResponse, error)
	JoinBlock(context.Context, *JoinBlockRequest) (*JoinBlockResponse, error)
	CompactBlock(context.Context, *CompactBlockRequest) (*CompactBlockResponse, error)
	GetCluster(context.Context, *GetClusterRequest) (*GetClusterResponse, error)
	WatchCluster(*WatchClusterRequest, Store_WatchClusterServer) error
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).List(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).Get(m, &storeGetServer{stream})
}

type Store_GetServer interface {
	Send(*GetResponse) error
	grpc.ServerStream
}

type storeGetServer struct {
	grpc.ServerStream
}

func (x *storeGetServer) Send(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Store_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServer).Add(&storeAddServer{stream})
}

type Store_AddServer interface {
	Send(*AddResponse) error
	Recv() (*AddRequest, error)
	grpc.ServerStream
}

type storeAddServer struct {
	grpc.ServerStream
}

func (x *storeAddServer) Send(m *AddResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeAddServer) Recv() (*AddRequest, error) {
	m := new(AddRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Store_UpdateRetentionPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UpdateRetentionPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).UpdateRetentionPolicy(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_LookupBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LookupBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).LookupBlock(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_SplitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SplitBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).SplitBlock(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_JoinBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(JoinBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).JoinBlock(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_CompactBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CompactBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).CompactBlock(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_GetCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(StoreServer).GetCluster(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Store_WatchCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchClusterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).WatchCluster(m, &storeWatchClusterServer{stream})
}

type Store_WatchClusterServer interface {
	Send(*WatchClusterResponse) error
	grpc.ServerStream
}

type storeWatchClusterServer struct {
	grpc.ServerStream
}

func (x *storeWatchClusterServer) Send(m *WatchClusterResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openinstrument.proto.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Store_List_Handler,
		},
		{
			MethodName: "UpdateRetentionPolicy",
			Handler:    _Store_UpdateRetentionPolicy_Handler,
		},
		{
			MethodName: "LookupBlock",
			Handler:    _Store_LookupBlock_Handler,
		},
		{
			MethodName: "SplitBlock",
			Handler:    _Store_SplitBlock_Handler,
		},
		{
			MethodName: "JoinBlock",
			Handler:    _Store_JoinBlock_Handler,
		},
		{
			MethodName: "CompactBlock",
			Handler:    _Store_CompactBlock_Handler,
		},
		{
			MethodName: "GetCluster",
			Handler:    _Store_GetCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Store_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Add",
			Handler:       _Store_Add_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchCluster",
			Handler:       _Store_WatchCluster_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 2008 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0x5f, 0x93, 0xdb, 0x56,
	0x15, 0xaf, 0xfc, 0xdf, 0xc7, 0xbb, 0x1b, 0xe5, 0x6e, 0x02, 0x1e, 0xa7, 0xcc, 0x34, 0xa2, 0xd0,
	0x6d, 0x87, 0xba, 0x61, 0x43, 0xa0, 0x74, 0xd2, 0x36, 0xce, 0x5a, 0x6c, 0xdc, 0xd8, 0xb2, 0xb1,
	0xbd, 0x1b, 0xca, 0x30, 0x78, 0xb4, 0xd6, 0x5d, 0x57, 0x13, 0x5b, 0x32, 0x92, 0x1c, 0xb2, 0x3c,
	0xf1, 0xc4, 0x47, 0x60, 0x78, 0xe0, 0x8d, 0x07, 0x86, 0xb7, 0x32, 0x7c, 0x08, 0x1e, 0x98, 0x61,
	0x86, 0x8f, 0xc2, 0x0b, 0xbc, 0x72, 0xee, 0x1f, 0x59, 0x92, 0xd7, 0xf6, 0x6a, 0x37, 0xc3, 0x9b,
	0x74, 0x75, 0xef, 0xef, 0x9e, 0xf3, 0x3b, 0xff, 0x05, 0x77, 0xdc, 0x39, 0x75, 0x6c, 0xc7, 0x0f,
	0xbc, 0xc5, 0x8c, 0x3a, 0x41, 0x7d, 0xee, 0xb9, 0x81, 0x4b, 0xd6, 0xae, 0x6a, 0xc7, 0x00, 0x6d,
	0x77, 0xd2, 0xa1, 0xbe, 0x6f, 0x4e, 0x28, 0xb9, 0x0d, 0xe5, 0xc0, 0x9e, 0x51, 0x3f, 0x30, 0x67,
	0xf3, 0xaa, 0xf2, 0x8e, 0x72, 0x90, 0x23, 0x77, 0x61, 0x97, 0x3a, 0xd6, 0x28, 0x5a, 0xce, 0xf2,
	0xe5, 0x5b, 0x50, 0x9c, 0x89, 0x43, 0xd5, 0x0c, 0x2e, 0x94, 0xb5, 0x4f, 0x61, 0xa7, 0x3b, 0xa7,
	0x9e, 0x19, 0xd8, 0xae, 0x83, 0x88, 0xe4, 0x43, 0xc8, 0x4e, 0xdd, 0x09, 0x82, 0x64, 0x0f, 0x2a,
	0x87, 0xef, 0xd4, 0xd7, 0x5d, 0x5e, 0x8f, 0x6e, 0xd6, 0xfe, 0x9c, 0x81, 0xbd, 0x41, 0xe0, 0x51,
	0x73, 0x76, 0x6a, 0x7a, 0xb6, 0x79, 0x36, 0xa5, 0x64, 0x07, 0x72, 0x8e, 0x39, 0xa3, 0x5c, 0x8e,
	0x32, 0xf9, 0x0c, 0xf2, 0x53, 0xf3, 0x8c, 0x4e, 0xf1, 0x3a, 0x86, 0xf8, 0xd1, 0x7a, 0xc4, 0x24,
	0x44, 0xbd, 0xcd, 0x4e, 0xe8, 0x4e, 0xe0, 0x5d, 0x90, 0xc7, 0x90, 0x0b, 0x2e, 0xe6, 0x94, 0x8b,
	0xbf, 0x77, 0x58, 0x4f, 0x75, 0xfc, 0xd4, 0x9c, 0x2e, 0xe8, 0x10, 0x4f, 0x31, 0x16, 0x66, 0xb6,
	0x13, 0x63, 0x21, 0x87, 0x30, 0x59, 0xbe, 0x6c, 0xbe, 0x8e, 0x2d, 0xe7, 0xd9, 0x72, 0xed, 0x7b,
	0x48, 0x6a, 0x74, 0x73, 0x05, 0xb2, 0x2f, 0xe9, 0x85, 0x54, 0x63, 0x17, 0xf2, 0xaf, 0x18, 0xaa,
	0x60, 0xed, 0x93, 0xcc, 0xc7, 0x8a, 0xf6, 0x21, 0x94, 0xa3, 0x8b, 0x2a, 0x50, 0x3c, 0x31, 0x9e,
	0x1b, 0xdd, 0x17, 0x86, 0xfa, 0x16, 0x29, 0x43, 0xfe, 0xb8, 0x71, 0x72, 0xac, 0xab, 0x0a, 0x29,
	0x41, 0xae, 0xdf, 0x18, 0xea, 0x6a, 0x46, 0xfb, 0xef, 0x92, 0xa9, 0xce, 0x22, 0xe0, 0x74, 0x93,
	0x4f, 0xa5, 0x6e, 0x0a, 0xd7, 0x6d, 0x2b, 0x35, 0xe1, 0x99, 0xfa, 0x00, 0xc5, 0x9d, 0x8a, 0x3b,
	0x51, 0xa6, 0xb9, 0xe9, 0x99, 0x33, 0x2e, 0x93, 0x42, 0x3e, 0x80, 0xfc, 0xaf, 0x16, 0xd4, 0xbb,
	0xe0, 0x54, 0x55, 0x0e, 0xef, 0xad, 0x87, 0xfb, 0x29, 0xdb, 0x42, 0xee, 0xc1, 0x3e, 0x23, 0x60,
	0x62, 0xce, 0x47, 0xb6, 0x13, 0x50, 0x6f, 0xee, 0x4e, 0xcd, 0x80, 0x72, 0x76, 0x76, 0x49, 0x15,
	0x54, 0x9f, 0xdf, 0x32, 0x3a, 0xf7, 0x28, 0x42, 0x3a, 0xe3, 0x0b, 0x4e, 0xd0, 0xae, 0xf6, 0x37,
	0x05, 0x20, 0x26, 0x00, 0x2a, 0x67, 0x74, 0x0d, 0x1d, 0x35, 0xc6, 0xa7, 0x8e, 0xde, 0x30, 0x50,
	0xe1, 0x22, 0x64, 0x3b, 0x8d, 0x9f, 0xa9, 0x19, 0xfe, 0xd0, 0x32, 0xd4, 0xec, 0x92, 0x02, 0xe6,
	0x7c, 0x15, 0xf6, 0x34, 0x1a, 0xb4, 0x8e, 0x0d, 0xbd, 0xa9, 0xe6, 0xd9, 0x42, 0xcb, 0x18, 0xea,
	0xfd, 0x5e, 0xb7, 0xcd, 0x76, 0x14, 0xd8, 0xde, 0x76, 0x63, 0x30, 0x54, 0x8b, 0x8c, 0xc3, 0x9f,
	0xb4, 0xfa, 0xf8, 0x58, 0x42, 0x87, 0x2a, 0x75, 0x4e, 0xda, 0xc3, 0x56, 0xaf, 0xfd, 0xa5, 0x5a,
	0x66, 0xb8, 0x8d, 0x66, 0x53, 0x05, 0x8e, 0xdb, 0xed, 0x0e, 0xd5, 0x0a, 0xdb, 0xdb, 0xeb, 0xbe,
	0xd0, 0xfb, 0xea, 0x0e, 0x21, 0xb0, 0xd7, 0xe9, 0x9e, 0xb6, 0x8c, 0xe3, 0x51, 0xe3, 0x54, 0xef,
	0x37, 0xd0, 0x06, 0xbb, 0xda, 0x9f, 0x32, 0x70, 0x5b, 0xb0, 0xd8, 0x98, 0x4c, 0x3c, 0x3a, 0x11,
	0xe4, 0x1f, 0x25, 0xc8, 0x7f, 0xb4, 0x8d, 0xfc, 0xd8, 0xb1, 0x7a, 0xf8, 0xbc, 0x34, 0x41, 0xe4,
	0xdd, 0x65, 0xf2, 0x4d, 0xb8, 0x25, 0x99, 0xe3, 0xac, 0xa2, 0xc7, 0x70, 0x63, 0xec, 0x46, 0xa6,
	0xca, 0x25, 0x4d, 0x95, 0xe7, 0x41, 0xb1, 0xcd, 0x54, 0xda, 0x39, 0xec, 0x26, 0xef, 0x4c, 0xc7,
	0x3a, 0x40, 0xa1, 0xa3, 0x37, 0x5b, 0xf8, 0x35, 0xc7, 0x16, 0x07, 0x27, 0x1d, 0xe4, 0x1b, 0x17,
	0x07, 0xc3, 0x66, 0x53, 0x3f, 0x45, 0xaa, 0xf7, 0x00, 0x7a, 0x7a, 0xff, 0x48, 0x37, 0x86, 0xad,
	0xb6, 0xae, 0x16, 0xb5, 0x5f, 0x42, 0x9e, 0xbb, 0xf3, 0xba, 0x64, 0xa2, 0x42, 0xc1, 0x72, 0x17,
	0x18, 0x5a, 0xc2, 0xd5, 0x9e, 0xbd, 0xc5, 0x56, 0x50, 0x5a, 0xdb, 0x99, 0x70, 0x05, 0xcb, 0xb8,
	0x72, 0x29, 0xe1, 0x30, 0x55, 0x73, 0x4f, 0x8b, 0x32, 0x70, 0xb4, 0xbf, 0x28, 0x50, 0xe1, 0x17,
	0x08, 0x4e, 0xc9, 0x0f, 0xa1, 0xf4, 0x4a, 0x06, 0x2c, 0x47, 0xad, 0x1c, 0xbe, 0x9b, 0x26, 0xb8,
	0x19, 0x77, 0x22, 0x12, 0x73, 0xdb, 0xb8, 0x13, 0xaa, 0xe0, 0x1d, 0x33, 0x19, 0x38, 0x92, 0xea,
	0x77, 0xd3, 0x04, 0x99, 0xf6, 0x77, 0x05, 0xf2, 0x22, 0x50, 0xe2, 0x52, 0x2a, 0x57, 0x23, 0x2c,
	0xa5, 0x8c, 0xdf, 0x9c, 0x49, 0x7f, 0x33, 0xa6, 0xbb, 0x8a, 0x19, 0x79, 0x1b, 0x92, 0xcb, 0x8e,
	0xbe, 0x97, 0xd2, 0x39, 0xd1, 0x2a, 0xa5, 0xb1, 0x8b, 0xdb, 0x4c, 0x27, 0xe0, 0xf4, 0x28, 0xda,
	0xd7, 0x19, 0x80, 0x63, 0x1a, 0xf4, 0x59, 0x1c, 0xfb, 0x41, 0xe4, 0x78, 0xca, 0xd5, 0x39, 0xe2,
	0x93, 0x98, 0xea, 0xe5, 0xf4, 0x06, 0x7a, 0x9a, 0xa9, 0x2a, 0xec, 0xec, 0x52, 0xfd, 0x42, 0x7a,
	0xf5, 0xf9, 0xd9, 0x27, 0x49, 0x0a, 0x8a, 0xd7, 0xa2, 0x80, 0x23, 0xc8, 0xf4, 0x1e, 0x4a, 0xef,
	0x57, 0x4b, 0x3c, 0x08, 0xd1, 0xb1, 0xcf, 0x5d, 0xef, 0xd7, 0xa6, 0x67, 0x51, 0xab, 0x0a, 0xb8,
	0x54, 0xc2, 0x74, 0x01, 0x62, 0x27, 0x7a, 0x8b, 0x5f, 0xad, 0xf0, 0x24, 0xf7, 0x07, 0x74, 0x54,
	0x4e, 0x99, 0x3f, 0x47, 0x2e, 0x29, 0x2b, 0x99, 0xfe, 0x62, 0x3c, 0xc6, 0x82, 0xc7, 0x59, 0x2b,
	0x91, 0x3b, 0xb0, 0x43, 0x3d, 0xcf, 0xf5, 0x12, 0x85, 0x94, 0x7c, 0x9f, 0x47, 0x04, 0x4a, 0x23,
	0x8d, 0x76, 0x7f, 0x8b, 0x63, 0xca, 0x10, 0xf8, 0x08, 0xf2, 0x2c, 0x5c, 0x3c, 0xe9, 0xca, 0x57,
	0x57, 0xdb, 0x3e, 0x40, 0xc3, 0xb2, 0x42, 0x63, 0x46, 0x37, 0x2a, 0x69, 0x6f, 0x4c, 0x50, 0xc0,
	0xe4, 0x2e, 0x69, 0xbf, 0x43, 0x75, 0x39, 0xe8, 0xf5, 0xd4, 0x5d, 0xca, 0x9e, 0x4d, 0x27, 0x3b,
	0xc7, 0xe5, 0x42, 0xf8, 0xb2, 0xcc, 0xec, 0x41, 0x41, 0xf2, 0x2e, 0x8a, 0xcb, 0xcf, 0xa1, 0xd2,
	0xb6, 0xfd, 0xa5, 0xab, 0xfe, 0x00, 0x0a, 0x73, 0x8f, 0x9e, 0xdb, 0xaf, 0x65, 0x3d, 0x4b, 0x17,
	0x77, 0x97, 0x4c, 0x9f, 0xe1, 0xd8, 0xff, 0x52, 0x60, 0x47, 0x80, 0xff, 0xdf, 0x8d, 0x1a, 0xcf,
	0x18, 0xb9, 0x6b, 0x64, 0x8c, 0x25, 0xa1, 0xf9, 0x94, 0xce, 0xf0, 0x47, 0x05, 0xd4, 0xa7, 0x53,
	0x77, 0xfc, 0xf2, 0x19, 0x35, 0x2d, 0xea, 0xb5, 0x1c, 0x8b, 0xbe, 0x5e, 0xc9, 0x57, 0xe9, 0x79,
	0x43, 0x63, 0xb8, 0xe7, 0xe7, 0x3e, 0x0d, 0xb8, 0xe2, 0x05, 0x16, 0x18, 0xce, 0x62, 0x16, 0x06,
	0x06, 0xb3, 0x40, 0x71, 0x7d, 0x33, 0x55, 0x58, 0xdf, 0x4c, 0x15, 0xb4, 0xdf, 0xa3, 0x5f, 0xc5,
	0xc4, 0x63, 0x8c, 0xbf, 0xa2, 0x9e, 0x2f, 0x32, 0x02, 0xb3, 0x3f, 0x2b, 0x96, 0x81, 0xe9, 0x05,
	0xa3, 0x2b, 0x5b, 0xd7, 0x0c, 0x5f, 0x7e, 0x04, 0x79, 0x9b, 0xe9, 0x28, 0x09, 0xfa, 0xee, 0x7a,
	0xbd, 0x2e, 0x31, 0x82, 0xf7, 0x32, 0x34, 0xd6, 0xca, 0x15, 0x79, 0xc7, 0xfb, 0x1f, 0x05, 0xf6,
	0xfb, 0x34, 0xc0, 0x23, 0x28, 0x4b, 0xcf, 0x9d, 0xda, 0xe3, 0x8b, 0x56, 0x40, 0x67, 0x37, 0x4e,
	0xf5, 0x78, 0xc1, 0xd8, 0x9d, 0xb1, 0xef, 0xb2, 0x0b, 0x78, 0x82, 0x9e, 0xcb, 0x61, 0x65, 0xd3,
	0xfa, 0x60, 0x3d, 0xcc, 0x1a, 0x19, 0xea, 0x43, 0xd3, 0x9b, 0xd0, 0x20, 0x51, 0x3d, 0x72, 0xd7,
	0xa8, 0x5b, 0x6f, 0x43, 0x41, 0x22, 0x60, 0x6b, 0xf0, 0x5c, 0xd7, 0x7b, 0xa2, 0x49, 0x68, 0xf6,
	0xbb, 0x3d, 0x55, 0xc1, 0x0a, 0x7f, 0x6b, 0xe5, 0x4e, 0xf2, 0xe3, 0xa5, 0xa8, 0x42, 0xe3, 0xf7,
	0x53, 0x8b, 0xca, 0x6a, 0xcd, 0xb2, 0xc9, 0x11, 0x41, 0xf6, 0x4f, 0x05, 0x76, 0x8f, 0xa6, 0x0b,
	0x1f, 0x17, 0x3b, 0x74, 0x76, 0x26, 0x6c, 0x6e, 0x5a, 0x96, 0x17, 0x46, 0x59, 0x99, 0x7c, 0x0c,
	0x79, 0x34, 0x69, 0x20, 0xc2, 0x6b, 0x6f, 0xd3, 0x75, 0x09, 0x10, 0xd4, 0x11, 0x0f, 0xb0, 0xf8,
	0x9c, 0x9a, 0x7e, 0x30, 0x5a, 0xcc, 0x2d, 0x7c, 0xb5, 0xe4, 0x38, 0x13, 0xce, 0x1a, 0x39, 0x6e,
	0x59, 0x03, 0xf2, 0x62, 0x73, 0xa2, 0x1b, 0x67, 0x3d, 0x65, 0xb7, 0xd1, 0x14, 0x5d, 0x52, 0xff,
	0xc4, 0xc0, 0x2e, 0x09, 0x1b, 0xc6, 0x66, 0xbf, 0xc1, 0xfb, 0x24, 0x6c, 0x2e, 0xfb, 0x7a, 0xa3,
	0xd9, 0x35, 0xb0, 0xb9, 0x64, 0x78, 0xa5, 0xc1, 0xb3, 0x93, 0x61, 0x93, 0x9d, 0xcc, 0x6b, 0x7f,
	0x8d, 0x14, 0x3a, 0x72, 0x9d, 0x73, 0x7b, 0x42, 0x1e, 0x62, 0x3e, 0x40, 0x95, 0x31, 0x4a, 0x05,
	0x5f, 0xdf, 0x4e, 0xa1, 0x00, 0x2b, 0xba, 0x67, 0xcc, 0x2b, 0x65, 0x23, 0x70, 0x6f, 0x8b, 0xe3,
	0x92, 0xcf, 0x41, 0xf5, 0x42, 0xb2, 0x47, 0x31, 0x2f, 0xaa, 0x1c, 0x7e, 0x27, 0x95, 0x69, 0xb4,
	0xaf, 0x73, 0x90, 0x17, 0x50, 0x98, 0xbb, 0xbe, 0xe2, 0x71, 0x50, 0xbd, 0xcd, 0x01, 0xee, 0x5f,
	0x19, 0x30, 0x18, 0xf4, 0x19, 0xdb, 0x92, 0xa6, 0x8a, 0xc5, 0x8d, 0xc8, 0x85, 0x0f, 0x42, 0xdb,
	0x09, 0xaf, 0xde, 0x06, 0x27, 0x6d, 0x86, 0x11, 0xce, 0x23, 0x96, 0x5a, 0xa3, 0x64, 0xea, 0xff,
	0x06, 0xec, 0x85, 0x1f, 0xe2, 0x25, 0x80, 0xad, 0xe3, 0xf0, 0x39, 0x89, 0xed, 0x17, 0xa9, 0x02,
	0x33, 0x82, 0x5c, 0x97, 0xdb, 0x8b, 0xe1, 0xa0, 0xb2, 0x70, 0x56, 0x0e, 0x94, 0xc2, 0xdc, 0xb2,
	0xfc, 0x22, 0x8f, 0x94, 0xc3, 0x23, 0x18, 0xac, 0x73, 0x73, 0x1c, 0x8c, 0xac, 0x85, 0x98, 0x7a,
	0x79, 0x2b, 0x50, 0x26, 0x35, 0x20, 0xe1, 0x97, 0x28, 0x2d, 0xf1, 0x96, 0x20, 0x17, 0x3f, 0x15,
	0x66, 0xa6, 0xea, 0xce, 0xd2, 0x01, 0x5d, 0x8b, 0x56, 0x77, 0x39, 0x06, 0xee, 0xb3, 0x30, 0x67,
	0xd9, 0x0e, 0x07, 0x1e, 0xf1, 0x2f, 0x7b, 0xfc, 0xcb, 0xaa, 0xfb, 0xaa, 0xe1, 0x69, 0xdf, 0xfe,
	0x0d, 0xad, 0x12, 0x1e, 0x3f, 0xaf, 0xd6, 0xba, 0x2f, 0xbe, 0x30, 0xf7, 0xc5, 0x91, 0x46, 0x8c,
	0x93, 0xed, 0xd6, 0x29, 0x8e, 0x93, 0xac, 0x7d, 0x3f, 0xea, 0x76, 0x7a, 0x8d, 0xa3, 0x21, 0xfb,
	0x92, 0xc5, 0x09, 0xa3, 0xdc, 0x69, 0x1d, 0xe3, 0x78, 0xc5, 0x5e, 0x73, 0xec, 0xf5, 0xc4, 0x08,
	0xcf, 0xe5, 0x99, 0x5f, 0x8b, 0x57, 0x1c, 0xbb, 0x0a, 0xec, 0x63, 0x53, 0x1f, 0x0c, 0xfb, 0xdd,
	0x2f, 0xf1, 0x95, 0x75, 0xfe, 0xa4, 0xed, 0xba, 0x2f, 0x17, 0x73, 0x6e, 0xbb, 0xb0, 0xfe, 0xde,
	0xb4, 0x92, 0x60, 0x5e, 0xe0, 0xde, 0x3e, 0xb2, 0x2d, 0xf9, 0x8b, 0xa1, 0x01, 0xfb, 0x09, 0x7c,
	0x59, 0x82, 0x97, 0x61, 0xb1, 0xb5, 0x17, 0xe5, 0x67, 0xb4, 0xcf, 0x71, 0x82, 0x9b, 0x4f, 0xed,
	0x20, 0x21, 0xe1, 0x75, 0x00, 0x9e, 0x00, 0x89, 0x03, 0x5c, 0x16, 0xe1, 0xaa, 0xc8, 0xd4, 0x3e,
	0x03, 0xf5, 0x0b, 0xd7, 0x76, 0x6e, 0x2c, 0x01, 0xaa, 0x10, 0x3b, 0x7f, 0x03, 0x0e, 0x90, 0xc6,
	0x23, 0xe1, 0x84, 0x37, 0x96, 0xe1, 0x29, 0xdc, 0x49, 0x42, 0xdc, 0x40, 0x8c, 0x7d, 0xb8, 0x8d,
	0xdd, 0xb1, 0xcc, 0x70, 0x52, 0x08, 0xad, 0x05, 0x24, 0xbe, 0x28, 0x61, 0x31, 0x5b, 0x8e, 0x79,
	0xde, 0x94, 0xb8, 0xdb, 0xb3, 0xa5, 0x48, 0xb1, 0x0c, 0x8a, 0xf1, 0x94, 0xbc, 0x80, 0x41, 0xcd,
	0x78, 0x36, 0x4d, 0x05, 0x25, 0x12, 0xaf, 0xf6, 0x05, 0xec, 0x27, 0xa0, 0x22, 0xb1, 0x96, 0x58,
	0x69, 0x93, 0xb8, 0xf6, 0x1c, 0xee, 0x9c, 0xf0, 0xd8, 0xdd, 0x22, 0x58, 0x6a, 0xb0, 0x36, 0xdc,
	0x5d, 0x01, 0x7b, 0x13, 0xd1, 0xee, 0xc2, 0xfe, 0x0b, 0x33, 0x18, 0x7f, 0xb5, 0x62, 0x13, 0x94,
	0x38, 0xb9, 0xfc, 0x26, 0x56, 0xf9, 0xb7, 0x02, 0x6f, 0x0b, 0x91, 0x57, 0x0a, 0x4e, 0xc8, 0xc3,
	0x33, 0xc8, 0xb8, 0x73, 0xf9, 0x33, 0xe5, 0xf1, 0x7a, 0xc4, 0x6d, 0xe7, 0xeb, 0xcb, 0x9f, 0x90,
	0xe4, 0x47, 0x90, 0xb3, 0xb1, 0xc1, 0x90, 0x3f, 0x05, 0xae, 0xd7, 0x91, 0xcc, 0x5d, 0xdf, 0x96,
	0x83, 0x33, 0xcb, 0xa8, 0x8f, 0xa1, 0x1c, 0xe1, 0x26, 0xb2, 0x2a, 0x40, 0xa1, 0xd1, 0xeb, 0xe9,
	0x06, 0x6b, 0x0b, 0xf0, 0xb9, 0x65, 0x0c, 0xf4, 0xfe, 0x10, 0xd3, 0x2a, 0x3e, 0xf7, 0xf5, 0x4e,
	0x17, 0x53, 0x6c, 0x56, 0x3b, 0x85, 0x6f, 0x6d, 0x10, 0x59, 0x32, 0xf9, 0x28, 0xd6, 0x3d, 0xa5,
	0x2f, 0xd1, 0x87, 0xff, 0x28, 0xb2, 0x44, 0xef, 0x7a, 0x94, 0x74, 0x30, 0x9d, 0xe3, 0x54, 0x42,
	0x36, 0xd4, 0xd2, 0xd8, 0x38, 0x54, 0xd3, 0xb6, 0x6d, 0x91, 0xf2, 0xb4, 0x21, 0x8b, 0x51, 0x48,
	0x36, 0x8c, 0x0e, 0xd1, 0x6f, 0x80, 0xda, 0xfd, 0x2d, 0x3b, 0x04, 0xd6, 0x03, 0x85, 0x18, 0x90,
	0xc5, 0xb9, 0x70, 0x13, 0x5a, 0x34, 0x87, 0x6e, 0x42, 0x8b, 0x0d, 0x95, 0x07, 0x0a, 0xe2, 0xfd,
	0x56, 0x09, 0xbd, 0x7e, 0xb5, 0x0b, 0x3d, 0xbc, 0xbe, 0xbf, 0xd4, 0x1e, 0x5e, 0xeb, 0x8c, 0x24,
	0xe8, 0x0c, 0x47, 0xcc, 0xa8, 0x12, 0x91, 0x83, 0x4d, 0x33, 0xd6, 0x6a, 0x31, 0xac, 0xbd, 0x9f,
	0x62, 0xa7, 0xbc, 0x63, 0x04, 0x10, 0x55, 0x1a, 0xb2, 0xe9, 0xbf, 0xc5, 0x6a, 0x31, 0xab, 0x1d,
	0x5c, 0xbd, 0x51, 0x5e, 0xf0, 0x0b, 0x28, 0x2f, 0x0b, 0x09, 0xd9, 0x30, 0x05, 0xad, 0x56, 0xaa,
	0xda, 0x7b, 0x57, 0xee, 0x93, 0xe8, 0x14, 0x76, 0xe2, 0x25, 0x82, 0x6c, 0x6a, 0xd1, 0x2f, 0x57,
	0xa2, 0xda, 0x07, 0x69, 0xb6, 0x46, 0x2c, 0x45, 0x05, 0x63, 0x13, 0x4b, 0x97, 0xea, 0xcc, 0x26,
	0x96, 0xd6, 0xd4, 0x9e, 0x09, 0xec, 0xc4, 0xb3, 0xdf, 0x26, 0x3d, 0xd6, 0x24, 0xce, 0x4d, 0x7a,
	0xac, 0x4b, 0xa6, 0x0f, 0x94, 0xb3, 0x02, 0xff, 0xfa, 0xf0, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xe8, 0xb2, 0x1f, 0x1f, 0xbe, 0x19, 0x00, 0x00,
}
